### ISSUE TITLE
Crashes due to malformed data sent to StatsD plugin 

### ISSUE THREAD

**Issue by philipcristiano** [spotify/ffwd-ruby#5]
Using v0.1.2 and v0.1.4 logs are showing 

```
E, [2014-05-28T17:55:12.349142 #1089] ERROR -- FFWD::Plugin::Statsd::Connection: Failed to receive data
E, [2014-05-28T17:55:12.349352 #1089] ERROR -- FFWD::Plugin::Statsd::Connection: Caused by NameError: undefined local variable or method `log' for FFWD::Plugin::Statsd::Parser:Module
E, [2014-05-28T17:55:12.355965 #1089] ERROR -- FFWD::Plugin::Statsd::Connection:   /opt/rbenv/ffwd-all/versions/2.1.0/lib/ruby/gems/2.1.0/gems/ffwd-statsd-0.1.2/lib/ffwd/plugin/statsd/parser.rb:60:in `parse'
E, [2014-05-28T17:55:12.356075 #1089] ERROR -- FFWD::Plugin::Statsd::Connection:   /opt/rbenv/ffwd-all/versions/2.1.0/lib/ruby/gems/2.1.0/gems/ffwd-statsd-0.1.2/lib/ffwd/plugin/statsd/connection.rb:35:in `receive_data'
E, [2014-05-28T17:55:12.356143 #1089] ERROR -- FFWD::Plugin::Statsd::Connection:   /opt/rbenv/ffwd-all/versions/2.1.0/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
```

This appears to be the case where it is logging the malformed data and actually winds up crashing.

**Comment by willmeyer** [comment]
Aside from what is causing the invalid/unexpected type on the inbound message, one discrete issue is the FFWD::Logging isn't imported so that error handling case itself fails (the attempt to use the nonexistent log to log a warning).

**Comment by philipcristiano** [comment]
@udoprog thanks!
